version: '3'

services:
  node:
    build:
      context: ./node
    image: adrianofelisberto/nodeapp
    container_name: nodeapp
    volumes:
      - ./node/:/usr/src/app
    ports:
      - 8080:3000
    networks:
      - desafio-node
      
  # nginx:
  #   build: 
  #     context: ./nginx
  #   image: adrianofelisberto/nginx
  #   container_name: nginx
  #   networks: 
  #     - desafio-node
  #   ports: 
  #     - 8080:80

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio-node

networks:
  desafio-node:
    driver: bridge
