version: '3'

services:
  node:
    build:
      context: ./node
    image: adrianofelisberto/nodeapp
    container_name: nodeapp
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 10s node index.js
    networks:
      - desafio-node
    depends_on:
      - mysql
      
  nginx:
    build: 
      context: ./nginx
    image: adrianofelisberto/nginx
    container_name: nginx
    networks: 
      - desafio-node
    ports: 
      - 8080:80
    depends_on:
      - node

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio-node

networks:
  desafio-node:
    driver: bridge
